import createDOMPurify, { type WindowLike } from 'dompurify';
import { JSDOM } from 'jsdom';

const jsdomWindow = new JSDOM('').window as unknown as WindowLike;

const DOMPurify = createDOMPurify(jsdomWindow);

/**
 * Sanitise user-provided HTML to strip XSS vectors before persisting it in
 * any `*_html` column. Markdown source is stored separately in `body`/`content`.
 *
 * The allowlist covers three classes of content:
 *   1. Standard prose/markdown (p, em, strong, lists, tables, code).
 *   2. KaTeX HTML output for inline math — span/sub/sup with KaTeX classes,
 *      plus the MathML mirror that KaTeX emits for accessibility.
 *   3. Inline SVG diagrams (uploaded by admins or pre-rendered math). Path
 *      and primitive shape tags are allowed; <script>, <foreignObject>, and
 *      anything that can carry on*-style attributes are not.
 */
export function sanitizeHtml(html: string): string {
  if (!html) return html;
  return DOMPurify.sanitize(html, {
    ALLOWED_TAGS: [
      'b',
      'i',
      'em',
      'strong',
      'p',
      'br',
      'ul',
      'ol',
      'li',
      'code',
      'pre',
      'blockquote',
      'h1',
      'h2',
      'h3',
      'h4',
      'span',
      'img',
      'a',
      'figure',
      'figcaption',
      'table',
      'thead',
      'tbody',
      'tr',
      'td',
      'th',
      'hr',
      'sup',
      'sub',
      // KaTeX MathML mirror
      'math',
      'semantics',
      'annotation',
      'mrow',
      'mi',
      'mn',
      'mo',
      'ms',
      'mtext',
      'mfrac',
      'msup',
      'msub',
      'msubsup',
      'msqrt',
      'mroot',
      'mover',
      'munder',
      'munderover',
      'mtable',
      'mtr',
      'mtd',
      'mspace',
      'mstyle',
      'mpadded',
      // Inline SVG (math output + admin-uploaded diagrams)
      'svg',
      'g',
      'path',
      'line',
      'polyline',
      'polygon',
      'rect',
      'circle',
      'ellipse',
      'text',
      'tspan',
      'defs',
      'use',
      'marker',
      'title',
      'desc',
    ],
    ALLOWED_ATTR: [
      'href',
      'src',
      'alt',
      'title',
      'class',
      'style',
      'aria-hidden',
      // SVG attributes
      'xmlns',
      'xmlns:xlink',
      'xlink:href',
      'viewBox',
      'preserveAspectRatio',
      'width',
      'height',
      'd',
      'fill',
      'stroke',
      'stroke-width',
      'stroke-linecap',
      'stroke-linejoin',
      'stroke-dasharray',
      'transform',
      'x',
      'y',
      'x1',
      'y1',
      'x2',
      'y2',
      'cx',
      'cy',
      'r',
      'rx',
      'ry',
      'points',
      'font-family',
      'font-size',
      'font-weight',
      'font-style',
      'text-anchor',
      'dominant-baseline',
      'dx',
      'dy',
      'opacity',
      'id',
      // MathML
      'display',
      'mathvariant',
      'mathsize',
      'displaystyle',
      'scriptlevel',
      'open',
      'close',
      'separator',
      'lspace',
      'rspace',
      'maxsize',
      'minsize',
    ],
    ALLOW_DATA_ATTR: false,
  });
}
